application:
  subdomain: virtualhere-server
  background_task: true
  usb_accel: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: file:///lzcapp/pkg/content/help.html
  ingress:
    - protocol: tcp
      port: 7575
      service: virtualhere-server

services:
  virtualhere-server:
    # upstream: czyt/virtualhere-server:4.8.7
    image: czyt/virtualhere-server:4.8.7
    binds:
      - /lzcapp/var/data:/data
